#define BASE_LIGHT_INTENSITY 50
#define BUTTON_SHADOW_OFFSET 5

// Change to MOBILE_BUILD for touchscreen devices.
#define DESKTOP_BUILD
#define DEFAULT_WINDOW_WIDTH 800
#define DEFAULT_WINDOW_HEIGHT 640

#define ENTITY_MOVE_DELTA 3

#define FRAMERATE 30

#define ksColor sf::Color

#define LIGHT_INTENSITY_MULT 7

#define MAX_LIGHT_INTENSITY 3
#define MAX_PARTICLES 1000

#define TILE_HEIGHT 32
#define TILE_PER_LINE 9
#define TILE_WIDTH 32
